dist: trusty

language:
  cpp
   
compiler:
  - gcc # 4.8.4
  - clang # 3.5.0

before_install:
  - echo $LANG
  - export OMP_NUM_THREADS=4
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq && sudo apt-get install -qq; fi

install:
  ### LINUX
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -y install git mercurial subversion cmake libopencv-dev libcgal-dev libatlas-base-dev libsuitesparse-dev libboost-iostreams-dev libboost-program-options-dev libboost-system-dev libboost-serialization-dev libpng-dev libjpeg-dev libtiff-dev libglu1-mesa-dev; fi
  # Install the latest version of Eigen
  - if [ $TRAVIS_OS_NAME == linux ]; then hg clone https://bitbucket.org/eigen/eigen /tmp/eigen && cd /tmp/eigen && hg pull && hg update 3.2.6 && cd - && mkdir /tmp/eigen-build && cd /tmp/eigen-build && cmake /tmp/eigen && make && sudo make install && cd -; fi
  # Install the latest version of Ceres Solver
  - if [ $TRAVIS_OS_NAME == linux ]; then git clone --branch=master git://github.com/ceres-solver/ceres-solver.git /tmp/ceres-solver && mkdir /tmp/ceres-solver-build && cd /tmp/ceres-solver-build && cmake /tmp/ceres-solver -DMINIGLOG=ON -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF && make -j4 && sudo make install && cd -; fi
  ### OSX
  - if [ $TRAVIS_OS_NAME == osx ]; then sudo port install boost eigen3 opencv cgal ceres-solver; fi

before_script:
  - cd ..
  - main_path=`pwd`
  - svn checkout svn://svn.code.sf.net/p/vcg/code/trunk/vcglib vcglib
  - mkdir build
  - cd build
  - cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_DIR="$main_path/vcglib" -DOpenCV_CAN_BREAK_BINARY_COMPATIBILITY=OFF

script:
  - make -j4

after_success:
  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi

branches:
  only:
    - master
    - develop
    - travis

notifications:
  email: true

os:
  - linux
  #- osx
